config/routes.rb
Rails.application.routes.draw do
  root "artists#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :artists do
    resources :songs
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  mount_uploader :photo, ImageUploader
  has_many :songs

  validates :first_name, presence: true, length: {maximum: 50}
  validates :last_name, presence: true, length: {maximum: 50}
  validates :bio, presence: true
  # validates :photo, presence: true

  def self.order_by value
    order(value);
  end
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  validates :title, presence: true
  validates :duration, presence: true
  validates :genre, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    if params[:order_by]
      @artists = Artist.all.order_by params[:order_by]
    else
      @artists = Artist.all
    end
  end

  def show
    @artist = Artist.find(params[:id])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :set_artist, only: [:create]

  def new
    @song = Song.new
  end

  def create
    @song = @artist.songs.build(song_params)
    respond_to do |format|
      if @song.save
        format.html { redirect_to @artist.id, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :ok, location: @artist}
      else
        format.html { render @artist.id }
        format.json { render @artist.id, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to artist_path(song.artist), notice: 'Song was successfully removed.' }
      format.json { head :no_content }
    end
  end
  private

  def song_params
      params.require(:song).permit(:title, :duration, :genre)
  end

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end
  # Use callbacks to share common setup or constraints between actions.
   def set_song
     @song = Song.find(params[:id])
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper

  def genre artist
    !artist.songs[0].nil? ? artist.songs[0].genre : "undefined"
  end

  def artist_photo artist
    !artist.photo.nil? ? image_tag(artist.photo, class: "img-circle img-responsive") : image_tag("https://a2ua.com/singer/singer-003.jpg", class: "img-circle img-responsive")
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_artist.html.erb
<div class="col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
    	 <div class="well profile">
            <div class="col-sm-12">
                <div class="col-xs-12 col-sm-8">
                    <h2><%= "#{artist.first_name} #{artist.last_name}" %></h2>
                    <p><strong>Biography: </strong> <%= artist.bio.slice(0, 200) %></p>
                    <p><strong>Genre: </strong>
                        <span class="tags"><%= genre(artist) %></span>
                    </p>
                </div>
                <div class="col-xs-12 col-sm-4 text-center">
                    <figure>
                        <%= artist_photo artist %>
                        <figcaption class="ratings">
                            <p>Ratings
                            <a href="#">
                                <span class="fa fa-star"></span>
                            </a>
                            <a href="#">
                                <span class="fa fa-star"></span>
                            </a>
                            <a href="#">
                                <span class="fa fa-star"></span>
                            </a>
                            <a href="#">
                                <span class="fa fa-star"></span>
                            </a>
                            <a href="#">
                                 <span class="fa fa-star-o"></span>
                            </a>
                            </p>
                        </figcaption>
                    </figure>
                </div>
            </div>
            <div class="col-xs-12 divider text-center">
                <div class="col-xs-12 col-sm-4 emphasis">
                    <h2><strong> 20,7K </strong></h2>
                    <p><small>Followers</small></p>
                    <button class="btn btn-success btn-block"><span class="fa fa-plus-circle"></span> Follow </button>
                </div>
                <div class="col-xs-12 col-sm-4 emphasis">
                    <h2><strong>245</strong></h2>
                    <p><small>Following</small></p>
                    <a href="<%= artist_path(artist.id) %>"class="btn btn-info btn-block" id="show-profile"><span class="fa fa-user"></span> View Profile </a>
                </div>
                <div class="col-xs-12 col-sm-4 emphasis">
                    <h2><strong><%= artist.songs.length %></strong></h2>
                    <p><small>Songs</small></p>
                    <div class="btn-group dropup btn-block">
                      <button type="button" class="btn btn-primary"><span class="fa fa-gear"></span> Options </button>
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                      </button>
                      <ul class="dropdown-menu text-left" role="menu">
                        <li><a href="#"><span class="fa fa-envelope pull-right"></span> Send an email </a></li>
                        <li><a href="#"><span class="fa fa-list pull-right"></span> Add or remove from a list  </a></li>
                        <li class="divider"></li>
                        <li><a href="#"><span class="fa fa-warning pull-right"></span>Report this user for spam</a></li>
                        <li class="divider"></li>
                        <li><a href="#" class="btn disabled" role="button"> Unfollow </a></li>
                      </ul>
                    </div>
                </div>
            </div>
    	 </div>
     </div>

app/views/artists/_new_song.html.erb
<div class="page-wrapper">

    <div class="new-song">
        <div class="row">
            <div class="col-md-4 text-center">
              <a href="#" class="btn btn-danger pull-right" id="abort-song-creation"><span class="glyphicon glyphicon-remove"></span></a>
                <div class="box">
                    <h1>New Song</h1>
                    <div class="box-content">
                        <input type="text" id="song-title" class="tag-title" placeholder="< Song title >">
                        <hr/>
                        <br/>
                        <input type="text" id="song-genre" class="tag-title" placeholder="< Blues, Soul >">
                        <hr />
                        <a href="#" class="btn btn-default" id="create-new-song">Create</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/artists/index.html.erb
        <div class="content">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">Artists <%= form_tag artists_path, {:method => :get} do %> <label>Order by:</label><%= select_tag("order_by", "<option>select an option</option><option>first_name</option><option>last_name</option><option>created_at</option>".html_safe, :onchange => "this.form.submit();" ) %> <% end %></div>
                    <div class="panel-body">
                        <% @artists.each do |artist| %>
                          <%= render partial: 'artist', locals: { artist: artist } %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>

app/views/artists/show.html.erb
<div class="content">
    <div class="row">
        <div class="col-md-4 bg_blur ">
            <a href="#" class="follow_btn hidden-xs">Follow</a>
        </div>
        <div class="col-md-8  col-xs-12">
            <img src="<%= @artist.photo %>" class="img-thumbnail picture hidden-xs"/>
            <img src="<%= @artist.photo %>" class="img-thumbnail visible-xs picture_mob"/>
            <div class="header">
                <h1><%= "#{@artist.first_name} #{@artist.last_name}" %>
                </h1>
                <h4><%= genre @artist %></h4>
                <span><%= @artist.bio %></span>
            </div>
        </div>
    </div>
    <div class="row songs">
        <a href="#" class="btn btn-default pull-right" id="delete-all">Delete All</a>
        <a href="#" class="btn btn-default pull-left" id="add-song">
            <span class="glyphicon glyphicon-plus"></span>
        </a>
        <hr/>
        <% @artist.songs.each do |song| %>
        <div class="col-md-4 text-center song" id="<%= song.id %>">
            <div class="box">
                <div class="box-content">
                    <h1 class="tag-title"><%= song.title %></h1>
                    <hr/>
                    <h1 id="duration"><%= Time.at(song.duration/1000).strftime("%M:%S") %></h1>
                    <br/>
                    <a href="#" class="btn btn-primary">
                        <span class="glyphicon glyphicon-play-circle"></span>
                    </a>
                    <br/>
                    <hr/>
                    <a href="#" class="btn btn-default pull-right delete-song" id="<%= song.id %>">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                    <a href="#" class="btn btn-default pull-left"><%= song.genre %></a>
                </div>
            </div>
        </div>
        <% end %>
    </div>
  </div>
 <%= render 'new_song' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Shuffle</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>
    </head>

    <body>
        <div class="container">
            <div class="row">
                <div class="wrapper active">
                    <%= render 'shared/navbar' %>
                    <%= yield %>
                </div>
            </div>
        </div>
    </body>
</html>

app/views/shared/_navbar.html.erb
<div class="side-bar">
    <ul>
        <li class="menu-head">
            SHUFFLE
            <a href="#" class="push_menu">
                <span class="glyphicon glyphicon-align-justify pull-right"></span>
            </a>
        </li>
        <div class="menu">
            <li>
                <a href="<%= artists_path %>" class="active">Artists
                    <span class="glyphicon glyphicon-user pull-right"></span>
                </a>
            </li>
            <li>
                <a href="#" class="">Songs<span class="glyphicon glyphicon-cd pull-right"></span>
                </a>
            </li>
        </div>

    </ul>
</div>